# Generated by Django 5.0.6 on 2024-10-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_product',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
