# Generated by Django 5.2.3 on 2025-06-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_product',
            name='user',
        ),
    ]
